# Generated by Django 3.1 on 2022-11-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Created_date',
            new_name='created_date',
        ),
    ]
